In [1]:
from sklearn.neighbors import NearestNeighbors
import pandas as pd
import os
import numpy as np
import pickle

In [2]:
directory = "../../data/processed"

In [3]:
pd.set_option('display.max_columns', None)

In [9]:
file_path = os.path.join(directory, f"final_array.npy")
final = np.load(file_path)

In [10]:
len(final)

773

In [11]:
len(final[0])

47716

In [12]:
# Step 1: Fit the model
model_knn = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=4, n_jobs=-1)
model_knn.fit(final)

NearestNeighbors(algorithm='brute', metric='cosine', n_jobs=-1, n_neighbors=4)

In [22]:
# Step 2: Choose a row index
index = 10

In [36]:
# Step 3: Find the nearest neighbors
distances, indices = model_knn.kneighbors(final[index].reshape(1, -1), n_neighbors=6)

In [37]:
# Step 4: Extract indices and distances of the neighbors
neighbor_indices = indices[0][1:]
neighbor_distances = distances[0][1:]

In [25]:
file_path = '../../data/processed/merged.csv'

In [26]:
original_data = pd.read_csv(file_path)

In [38]:
# original_data

In [39]:
neighbor_indices

array([731, 381, 736, 593, 542])

In [28]:
# Step 5: Extract the rows corresponding to the nearest neighbors
nearest_rows = original_data.iloc[np.append(neighbor_indices,index) ]

In [29]:
nearest_rows

tour_id      productType  \
731  tour-d1491392-b97f-4f37-97cc-2becc5750994  connection_tour   
381  tour-ee54629c-0672-43ed-a48d-409aec74d9c7  connection_tour   
736  tour-d1491392-b97f-4f37-97cc-2becc5750994  connection_tour   
10   tour-3ee9c9e0-e8d1-4d0c-ad68-da50445941f1  connection_tour   

                   tour_name             brand activityLevel  reviewsRating  \
731     American Parks Trail  insightvacations        active            0.0   
381             The Bohemian  insightvacations           NaN            0.0   
736     American Parks Trail  insightvacations        active            0.0   
10   Hawaii with Oahu & Maui  insightvacations           NaN            0.0   

     reviewsTotal lowestOptionRoomType  lowestOptionPrice  \
731             0                 twin             4637.0   
381             0                 twin             2430.0   
736             0                 twin             4637.0   
10              0                 twin             3161.9   

     lowestOptionFullPrice                            fkSeasonId  \
731                 4637.0  8aa51d0e-4de1-4d6a-85a6-3ffe5ace5818   
381                 2700.0  d99e3691-3d70-4080-8e44-333128c63db3   
736                 4637.0  8aa51d0e-4de1-4d6a-85a6-3ffe5ace5818   
10                  3695.0  735b67f2-5078-4b55-a9f9-e22cb4a6bd85   

                           tour_option_id  \
731  f10b04ed-a1b4-41eb-9f62-801b11b9f4d0   
381  8042f8c6-cda5-47b7-83f1-e47916054681   
736  f3ef05f1-6771-4545-8a10-72689d5253c3   
10   02c339b5-eac7-4a1a-adb6-822c2c9d5dbe   

                                     tour_id.1 sourceTourOptionName  \
731  tour-d1491392-b97f-4f37-97cc-2becc5750994                  NaN   
381  tour-ee54629c-0672-43ed-a48d-409aec74d9c7                  NaN   
736  tour-d1491392-b97f-4f37-97cc-2becc5750994                  NaN   
10   tour-3ee9c9e0-e8d1-4d0c-ad68-da50445941f1                  NaN   

     isPrivateRequest  maxPax  \
731                 0     NaN   
381                 0     NaN   
736                 0     NaN   
10                  0     NaN   

                                      tour_option_name  \
731  American Parks Trail - End Rapid City, Small G...   
381            The Bohemian -  End Vienna, Small Group   
736     American Parks Trail - End Denver, Small Group   
10   Hawaii with Oahu, Maui & the Big Island - Smal...   

                                           description travelInclusions  \
731  Experience the rugged and wild West during thi...              NaN   
381  Experience the best Europe has to offer with a...              NaN   
736  Experience the rugged and wild West during thi...              NaN   
10   Hawaii’s traditional greeting, Aloha, embodies...              NaN   

    diningInclusions    startLocationName startLocationCountryCode  \
731              NaN  Salt Lake City (UT)                      NaN   
381              NaN               Vienna                       AT   
736              NaN  Salt Lake City (UT)                      NaN   
10               NaN             Honolulu                      NaN   

     startLocationLongitude  startLocationLatitude endLocationName  \
731                     NaN                    NaN      Rapid City   
381               16.389599              48.200644          Vienna   
736                     NaN                    NaN     Denver (CO)   
10                      NaN                    NaN            Kona   

    endLocationCountryCode  endLocationLongitude  endLocationLatitude  \
731                    NaN                   NaN                  NaN   
381                     AT             16.389599            48.200644   
736                    NaN                   NaN                  NaN   
10                     NaN                   NaN                  NaN   

                                     countries_visited  minChildPriceAge  \
731                                      United States                 5   
381  Slovakia, Poland, Au

In [30]:
original_data.iloc[index]

tour_id                         tour-3ee9c9e0-e8d1-4d0c-ad68-da50445941f1
productType                                               connection_tour
tour_name                                         Hawaii with Oahu & Maui
brand                                                    insightvacations
activityLevel                                                         NaN
                                              ...                        
day_28_title                                                          NaN
day_28_description                                                    NaN
day_28_accommodation                                                  NaN
day_28_meals                                                          NaN
locations               [{'name': 'Maui', 'countryCode': 'US', 'longit...
Name: 10, Length: 144, dtype: object

In [34]:
from sklearn.metrics.pairwise import cosine_similarity

# Compute the cosine similarity between tours
similarity_matrix = cosine_similarity(final)

# Get the top-k similar tours for a given tour
tour_index = 10  # Index of the given tour
top_k = 5  # Number of similar tours to retrieve
similar_tours = similarity_matrix[tour_index].argsort()[::-1][:top_k + 1][1:]

In [35]:
similar_tours

array([731, 381, 736, 593, 542])

In [40]:
neighbor_indices

array([731, 381, 736, 593, 542])

In [43]:
with open('../../models/nearest_neighbors_all_features.pkl', 'wb') as model_file:
    pickle.dump(model_knn, model_file)